### ISSUE TITLE
Style tweaks

### ISSUE THREAD

**Issue by bhauer** [evermoredev/everpaste#1]
This Pastebin looks terrific.  I have a few style tweaks I'd like to request.  These are based almost entirely on space efficiency, understanding that they compromise the appearance slightly.

* Reduce line spacing in the code viewer.  Since this is a table, something like border-collapse: collapse may be sufficient.  But even then, there's a lot of spacing between lines so some more tweaks may be needed.  The intent here is to maximize the amount of text that can be viewed without scrolling (without sacrificing too much readability of course).  Overall, lines could probably be about 4px to 6px closer without looking too close to my eye.
* Reduce title padding in the code viewer.  Maybe all the way to 0px since code-document still has a top margin.  This makes the non-body "chrome" very compact.
* Although not too important, I would also reduce the margins and padding on the edit view.
* On the edit view, consider giving the two input boxes (name and expiration) colors that match the main text input area.

**Comment by NateBrady23** [comment]
Woo on first issue! All of these were definitely valid design issues. I've updated the styles according to all of these bullet points.
