### ISSUE TITLE
[feature request] Upload from clipboard

### ISSUE THREAD

**Issue by cmsimike** [evermoredev/everpaste#16]
First - thank you very much for the file upload functionality! 

A feature request, for when you have time. On OSX, you have the ability to take a screen shot directly to your keyboard. I would love to be able to do that, and paste directly into your app, rather than need to save the image to disk, and then upload that.

**Comment by NateBrady23** [comment]
[Feature is live in 0.11.0](https://github.com/evermoredev/everpaste/releases/tag/0.11.0)
