### ISSUE TITLE
Name/expiration not remembered long enough

### ISSUE THREAD

**Issue by cmsimike** [evermoredev/everpaste#7]
It looks like both 'name' and 'expiration' values are put into cookie storage with an expiration of 'session' meaning those values will expire once my browser session does. A longer expiration time might be useful here.

**Comment by NateBrady23** [comment]
@cmsimike Thanks! Just bundled this fix in to the latest release This is done! https://github.com/everlib/everpaste/releases/tag/0.3.0 (and it's live at TE - it also saves your public/private choice now too, as there's a new public list view)
